// Generated by scripts/generate_chat_languages.py from shared/chat_languages.json.
// Do not edit by hand.

export const CHAT_LANGUAGES = [
  { code: 'en', label: 'English', speech: 'en-US' },
  { code: 'es', label: 'Spanish', speech: 'es-ES' },
  { code: 'fr', label: 'French', speech: 'fr-FR' },
] as const

export type ChatLanguageCode = 'en' | 'es' | 'fr'

export function languageByCode(code: string) {
  return CHAT_LANGUAGES.find((language) => language.code === code) ?? CHAT_LANGUAGES[0]
}
