"""Supported chat language contract shared by chat, voice, and export APIs.

Generated by scripts/generate_chat_languages.py from shared/chat_languages.json.
Do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, TypedDict

ChatLanguageCode = Literal["en", "es", "fr"]


class ChatLanguage(TypedDict):
    code: ChatLanguageCode
    label: str
    speech: str


CHAT_LANGUAGES: tuple[ChatLanguage, ...] = (
    {"code": "en", "label": "English", "speech": "en-US"},
    {"code": "es", "label": "Spanish", "speech": "es-ES"},
    {"code": "fr", "label": "French", "speech": "fr-FR"},
)

SUPPORTED_LANGUAGES: dict[ChatLanguageCode, str] = {
    language["code"]: language["label"] for language in CHAT_LANGUAGES
}
