import type { ChatLanguageCode } from '@/lib/chatLanguages'

export interface LoginRequest {
  username: string
  password: string
}

export interface TokenResponse {
  access_token: string
  token_type: string
}

export interface DocumentListResponse {
  documents: string[]
  count: number
}

export interface UploadResponse {
  filename: string
  chunks_indexed: number
  message: string
}

export interface QueryRequest {
  question: string
  mode?: 'simple' | 'agentic'
  language?: ChatLanguageCode
  history?: QueryHistoryMessage[]
}

export interface Citation {
  source: string
  chunk_index: number
  text: string
}

export interface QueryResponse {
  answer: string
  sources: string[]
  citations?: Citation[]
  validation: 'VALID' | 'NEEDS_REVISION'
  tokens_used: number
  mode: 'simple' | 'agentic'
  language?: string
  retry_count?: number
  latency_ms?: number
  trace?: AgentTrace | null
  output_flagged?: boolean
}

export interface QueryHistoryMessage {
  role: 'user' | 'assistant'
  content: string
}

export interface AgentTrace {
  original_question: string
  refined_query: string
  chunks_found: number
  validation_reason: string
  retries: number
  chunks_after_grading: number
  chunks_after_rerank: number
  hyde_tokens: number
  hyde_latency_ms: number
  grader_tokens: number
  grader_latency_ms: number
  reranker_latency_ms: number
  planner_tokens: number
  generator_tokens: number
  validator_tokens: number
  planner_latency_ms: number
  generator_latency_ms: number
  validator_latency_ms: number
  planner_model: string
  generator_model: string
  validator_model: string
  hypothetical_answer: string   // HyDE passage generated by hyde_node
  query_variants: string[]      // 2 alternative phrasings from planner_node
}

export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  input_method?: 'text' | 'voice'
  language?: string
  sources?: string[]
  citations?: Citation[]
  validation?: 'VALID' | 'NEEDS_REVISION'
  tokens_used?: number
  mode?: 'simple' | 'agentic'
  timestamp: Date
  retry_count?: number
  latency_ms?: number
  trace?: AgentTrace | null
  output_flagged?: boolean
  error?: boolean
}

export interface ChatVoiceExportMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
  origin?: 'typed' | 'voice'
}

export interface ChatVoiceExportRequest {
  text?: string
  transcript?: string
  messages?: ChatVoiceExportMessage[]
  voice?: string
  language?: ChatLanguageCode
  defer?: boolean
}

export interface ChatVoiceExportResponse {
  audio_base64: string
  audio_mime_type: string
  audio_format: 'mp3'
  transcript: string
  redacted: boolean
  expires_at?: string | null
  mode?: 'sync' | 'async'
}

export type ChatVoiceExportJobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled' | 'expired'

export interface ChatVoiceExportJobPolicy {
  max_retries: number
  timeout_seconds: number
  retry_after_seconds: number
  artifact_ttl_seconds: number
}

export interface ChatVoiceExportAcceptedResponse {
  job_id: string
  status: ChatVoiceExportJobStatus
  status_url: string
  cancel_url: string
  expires_at: string
  artifact_expires_at: string
  retry_after_seconds: number
  policy: ChatVoiceExportJobPolicy
}

export interface ChatVoiceExportArtifact {
  audio_base64: string
  audio_mime_type: string
  audio_format: 'mp3'
  expires_at: string
}

export interface ChatVoiceExportJobResponse {
  job_id: string
  status: ChatVoiceExportJobStatus
  created_at: string
  updated_at: string
  expires_at: string
  artifact_expires_at: string
  retry_count: number
  policy: ChatVoiceExportJobPolicy
  artifact: ChatVoiceExportArtifact | null
  redacted?: boolean
  error: { code: string; message: string } | null
}

export interface TranscriptRedactionRequest {
  text?: string
  transcript?: string
  messages?: ChatVoiceExportMessage[]
  language?: ChatLanguageCode
}

export interface TranscriptRedactionResponse {
  transcript: string
  redacted: boolean
}

export interface ApiError {
  detail: string | Record<string, string | number | boolean>
}

export interface SettingsResponse {
  // Section 1 — AI Model (all users)
  model: string
  embedding_model: string
  api_key_masked: string
  api_key_source: 'runtime' | 'environment' | 'not_configured'
  allowed_models: string[]
  allowed_embedding_models: string[]
  // Section 2 — Per-node models (admin only)
  planner_model: string
  generator_model: string
  validator_model: string
  // Section 3 — Retrieval (admin only)
  retriever_k: number
  similarity_score_threshold: number
  retriever_use_mmr: boolean
  retriever_fetch_k: number
  max_context_chunks: number
  // Section 4 — Generation limits (admin only)
  max_completion_tokens: number
  token_budget_warning_threshold: number
  // Section 5 — LangSmith observability (admin only)
  langchain_tracing_v2: boolean
  langchain_api_key_masked: string
  langchain_project: string
  // Section 6 — Vector store / Pinecone (admins and one-time guest settings)
  vector_store_type: 'chroma' | 'memory' | 'blob' | 'pinecone'
  file_store_type: 'local' | 'blob' | string
  pinecone_api_key_masked: string
  pinecone_api_key_source: 'runtime' | 'environment' | 'not_configured'
  pinecone_index_name: string
  pinecone_namespace: string
  pinecone_cloud: string
  pinecone_region: string
  blob_read_write_token_masked: string
  blob_read_write_token_source: 'runtime' | 'environment' | 'not_configured'
  guest_settings_locked?: boolean
  guest_settings_recoverable?: boolean
  guest_settings_reason?: string
  // Section 7 — Pipeline feature flags (admin only)
  retriever_hybrid_bm25: boolean
  relevance_grader_enabled: boolean
  ragas_evaluation_enabled: boolean
  reranker_type: string
  allowed_reranker_types: string[]
  reranker_judge_model: string
  allowed_judge_models: string[]
  chunker_type: string
  chunk_size: number
  chunk_overlap: number
  allowed_chunker_types: string[]
  // Section 8 — Environment / capability flags
  is_vercel?: boolean
  supports_cross_encoder?: boolean
  guest_doc_retention_hours?: number
  // Section 9 — Pipeline config (read-only informational)
  retriever_fusion_mode?: string
  reranker_top_k?: number
  semantic_breakpoint_threshold_type?: string
  max_query_length?: number
  query_rate_limit_per_minute?: number
  max_upload_size_mb?: number
  guest_max_upload_size_mb?: number
  guest_max_indexed_documents?: number
  // Guest session limits
  guest_session_ttl_minutes?: number
}

export interface SettingsUpdateRequest {
  // Section 1
  api_key?: string
  model?: string
  embedding_model?: string
  // Section 2
  planner_model?: string
  generator_model?: string
  validator_model?: string
  // Section 3
  retriever_k?: number
  similarity_score_threshold?: number
  retriever_use_mmr?: boolean
  retriever_fetch_k?: number
  max_context_chunks?: number
  // Section 4
  max_completion_tokens?: number
  token_budget_warning_threshold?: number
  // Section 5
  langchain_tracing_v2?: boolean
  langchain_api_key?: string
  langchain_project?: string
  // Section 6
  pinecone_api_key?: string
  pinecone_index_name?: string
  pinecone_namespace?: string
  pinecone_cloud?: string
  pinecone_region?: string
  blob_read_write_token?: string
  // Section 7 — Pipeline feature flags (admin only)
  retriever_hybrid_bm25?: boolean
  relevance_grader_enabled?: boolean
  ragas_evaluation_enabled?: boolean
  reranker_type?: string
  reranker_judge_model?: string
  chunker_type?: string
  chunk_size?: number
  chunk_overlap?: number
}

export interface DocumentMetadataItem {
  filename: string
  chunk_count: number
  uploaded_at: string | null
  owner_username: string | null
  availability: 'usable' | 'stale' | 'unknown'
}

export interface DocumentMetadataResponse {
  documents: DocumentMetadataItem[]
  count: number
}

export interface DocumentChunksResponse {
  filename: string
  chunks: string[]
  total_chunks: number
}

export interface DocumentContentResponse {
  filename: string
  content: string
  word_count: number
}

export interface DocumentSuggestionsResponse {
  suggestions: string[]
}

export interface GuardrailRule {
  id: string
  name: string
  description: string
  type: 'word' | 'topic' | 'regex'
  target: 'input' | 'output' | 'both'
  action: 'block' | 'flag' | 'redact'
  severity: 'low' | 'medium' | 'high'
  enabled: boolean
  builtin: boolean
  words: string[]
  keywords: string[]
  pattern: string
  replacement: string
}

export interface GuardrailRuleCreate {
  name: string
  description?: string
  type: 'word' | 'topic' | 'regex'
  target: 'input' | 'output' | 'both'
  action: 'block' | 'flag' | 'redact'
  severity?: 'low' | 'medium' | 'high'
  enabled?: boolean
  words?: string[]
  keywords?: string[]
  pattern?: string
  replacement?: string
}

export interface GuardrailRuleUpdate {
  name?: string
  description?: string
  action?: 'block' | 'flag' | 'redact'
  enabled?: boolean
  words?: string[]
  keywords?: string[]
  pattern?: string
  replacement?: string
  severity?: string
}

export interface GuardrailCheckRequest {
  text: string
  target: 'input' | 'output' | 'both'
}

export interface GuardrailCheckResponse {
  allowed: boolean
  modified_text: string
  flagged: boolean
  violations: Array<{ rule_id: string; rule_name: string; action: string; severity: string }>
}

export interface RagasScores {
  faithfulness: number
  answer_relevancy: number
  context_precision: number
  context_recall: number
  evaluated_at: string
  model: string
  num_samples: number
  has_results?: boolean
}
