#!/usr/bin/env python3
"""Generate chat language contracts from shared/chat_languages.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "chat_languages.json"
BACKEND_TARGET = ROOT / "backend" / "app" / "core" / "chat_languages.py"
FRONTEND_TARGET = ROOT / "frontend" / "src" / "lib" / "chatLanguages.ts"


def _load_languages() -> list[dict[str, str]]:
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(raw, list) or not raw:
        raise ValueError("chat_languages.json must contain a non-empty array")

    seen_codes: set[str] = set()
    languages: list[dict[str, str]] = []
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise ValueError(f"language entry {index} must be an object")
        language = _validate_language(item, index)
        if language["code"] in seen_codes:
            raise ValueError(f"duplicate language code: {language['code']}")
        seen_codes.add(language["code"])
        languages.append(language)
    return languages


def _validate_language(item: dict[str, Any], index: int) -> dict[str, str]:
    required = {"code", "label", "speech"}
    extra = set(item) - required
    missing = required - set(item)
    if missing or extra:
        raise ValueError(
            f"language entry {index} must contain only code, label, speech "
            f"(missing={sorted(missing)}, extra={sorted(extra)})"
        )

    language: dict[str, str] = {}
    for key in ("code", "label", "speech"):
        value = item[key]
        if not isinstance(value, str) or not value:
            raise ValueError(f"language entry {index}.{key} must be a non-empty string")
        language[key] = value
    return language


def _json_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _render_backend(languages: list[dict[str, str]]) -> str:
    codes = ", ".join(_json_string(language["code"]) for language in languages)
    entries = "\n".join(
        "    {"
        f"\"code\": {_json_string(language['code'])}, "
        f"\"label\": {_json_string(language['label'])}, "
        f"\"speech\": {_json_string(language['speech'])}"
        "},"
        for language in languages
    )
    return f'''"""Supported chat language contract shared by chat, voice, and export APIs.

Generated by scripts/generate_chat_languages.py from shared/chat_languages.json.
Do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, TypedDict

ChatLanguageCode = Literal[{codes}]


class ChatLanguage(TypedDict):
    code: ChatLanguageCode
    label: str
    speech: str


CHAT_LANGUAGES: tuple[ChatLanguage, ...] = (
{entries}
)

SUPPORTED_LANGUAGES: dict[ChatLanguageCode, str] = {{
    language["code"]: language["label"] for language in CHAT_LANGUAGES
}}
'''


def _render_frontend(languages: list[dict[str, str]]) -> str:
    code_union = " | ".join(
        _json_string(language["code"]).replace('"', "'") for language in languages
    )
    entries = "\n".join(
        "  { "
        f"code: {_json_string(language['code']).replace(chr(34), chr(39))}, "
        f"label: {_json_string(language['label']).replace(chr(34), chr(39))}, "
        f"speech: {_json_string(language['speech']).replace(chr(34), chr(39))} "
        "},"
        for language in languages
    )
    return f"""// Generated by scripts/generate_chat_languages.py from shared/chat_languages.json.
// Do not edit by hand.

export const CHAT_LANGUAGES = [
{entries}
] as const

export type ChatLanguageCode = {code_union}

export function languageByCode(code: string) {{
  return CHAT_LANGUAGES.find((language) => language.code === code) ?? CHAT_LANGUAGES[0]
}}
"""


def _targets(languages: list[dict[str, str]]) -> dict[Path, str]:
    return {
        BACKEND_TARGET: _render_backend(languages),
        FRONTEND_TARGET: _render_frontend(languages),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    try:
        targets = _targets(_load_languages())
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"chat language generation failed: {exc}", file=sys.stderr)
        return 1

    stale: list[Path] = []
    for path, content in targets.items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(content, encoding="utf-8")

    if stale:
        print("stale generated chat language contract files:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("run: python3 scripts/generate_chat_languages.py", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
